version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    networks:
      - default
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    links:
      - db
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
        - db:db
    ports:
      - 8080:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password